CREATE TABLE Ecommerce_Sales_Analysis(
Row_ID int,
Order_ID varchar(50),
Year int,
Order_Date date,
Ship_Date date,
Ship_Mode varchar(20),
Customer_ID varchar(20),
Customer_Name varchar(50),
Segment varchar(20),
Country varchar(20),
City varchar(20),
State varchar(20),
Postal_Code int,
Region varchar(20),
Product_ID varchar(20),
Category varchar(20),
Sub_Category varchar(20),
Product_Name varchar(50),
Sales decimal(10,4),
Quantity int,
Discount decimal(2,1),
profit decimal(10,4)
);